/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButtonTabs: typeof import('./src/components/BaseButtonTabs/BaseButtonTabs.vue')['default']
    BasePanel: typeof import('./src/components/BasePanel/BasePanel.vue')['default']
    BasePanelItem: typeof import('./src/components/BasePanel/BasePanelItem.vue')['default']
    Echarts: typeof import('./src/components/sencePanel/common/Echarts.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IScrollbar: typeof import('./src/components/IScrollbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SenceModal: typeof import('./src/components/sencePanel/common/senceModal.vue')['default']
    SencePanel: typeof import('./src/components/sencePanel/index.vue')['default']
  }
}
